--- #YAML:1.0
name:               LEOCHARRE-BogusFile
version:            1.01
abstract:           make file of x size with junk data
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          1
    Cwd:           3
    Exporter:      5
    Test::Simple:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
